Handle arrays in ActivityPub 'preview' field
This patch adds graceful handling for 'preview' fields that are encoded
as an array. The `Array(...)` conversion is skipped by Ruby
automatically if the underlying object is already an Array, therefore we
don't end up in a situation with nested arrays.

I found it out by having a look at the Sidekiq queues after the upgrade
to 4.6.8. A lot of dead jobs were in the queue, all of the
ActivityPub::ProcessingWorker. They all failed with:

    TypeError: no implicit conversion of String into Integer

In all cases, it was a PeerTube remote instance. PeerTube announces the
preview field as an array, breaking the string-based access. I verified
that the patch works as intended by copying the following URL into the
search form: https://video.blender.org/w/siQckdy9NyFGpZRThGfNE6

PeerTube instances do not have a summary field and their only preview is
of type=Image, therefore the presentation within Hometown doesn't
change -- this patch just fixes the parsing errors.